### ISSUE TITLE
[HOW-TO] Reduce delay after switching sensor modes.

### ISSUE THREAD

**Issue by h-huss** [raspberrypi/picamera2#1062]
**Describe what it is that you want to accomplish**
I want to switch from a 120fps sensor mode to a still configuration with as litte delay as possible.
(RPI 5 / HQ Camera / picamera2 0.3.18)

**Describe alternatives you've considered**

After the mode switch, the first image takes 500-700ms, after that, the following ones take 50 ms.
This is possibly related to the modeswitch itself, due to the eventloop its hard to identify the time-consuming operation.

Is this a limitation of the camera stack itself?

```python
import time
from picamera2 import Picamera2

picam = Picamera2()
cfgHighspeed = picam.create_video_configuration(
    {"size": (1024, 768)},
    controls={
        "FrameRate": 120,
        "ExposureTime": 20000,
        "AnalogueGain": 2.0,
        "ColourGains": (2.26, 2.48),
    },
)

cfgStill = picam.create_still_configuration(
    {"size": (2028, 1620)},
    controls={
        "ExposureTime": 20000,
        "AnalogueGain": 2.0,
        "ColourGains": (2.26, 2.48),
    },
)

picam.start()
for i in range(1, 40):
    picam.capture_metadata()


picam.switch_mode(cfgStill)

for i in range(1, 5):
    start = time.time()
    picam.capture_metadata()
    print(time.time() - start)
    # First request: 500 ms, following ones 50ms

```

**Comment by davidplowman** [comment]
Yes, unfortunately this is inherent in the camera stack, and is the same whether you're using Python or C++. Programming and starting a camera is a relatively slow process because there are lots of I2C register writes down in the kernel. It's quite dependent on the camera too, as some early frames may be invalid and get dropped by the system.

**Comment by sandyol55** [comment]
If you could use a 2028x1080 still format, rather than the full 2028x1520, there is an _experimental_ (Pi5 only) HQ camera driver that supports 120 fps at that resolution - so there'd be no need to switch configurations for the still capture.

(The even faster 10-bit modes at 2028x1520 and 2028x1080  currently aren't working, but the 12-bit modes are, and the 12-bit 2028x1080 mode supports 122 fps).

See [https://forums.raspberrypi.com/viewtopic.php?t=371216#p2227660](https://forums.raspberrypi.com/viewtopic.php?t=371216#p2227660)

**Comment by thenickdude** [comment]
This is an old issue, but just to contribute an improvement for someone else who finds the same. I found that my IMX477 spent 300ms just sending the I2C register writes to enter stills-taking mode from the viewfinder mode. 

When I looked closer, I realised it was re-sending the "common_regs", the register writes that need only be written once after poweron. The reason this was happening was that the power-saving for the IMX477 was turning off the sensor during the modeswitch (since it first stops streaming before it starts again in the new mode), so it had to be reinitialised from scratch.

Adding a udev rule improves that greatly by preventing the camera from going to sleep during the modeswitch:

```
/etc/udev/rules.d/98-imx477-no-pm.rules

ACTION=="add", SUBSYSTEM=="i2c", ATTR{name}=="imx477", ATTR{power/control}="on"
```

After that it only has to send 100ms of I2C commands to set up the sensor.

Finally, I patched the IMX477 driver to remember what register values it had sent before, so that when entering a new mode it didn't have to re-send any that matched the values they already had. This eliminated nearly all I2C register writes, the overhead due to I2C for me is now down to 10ms.

**Comment by 6by9** [comment]
A fair proportion of the delay will actually be due to the regulator configuration - https://github.com/raspberrypi/linux/blob/rpi-6.12.y/arch/arm/boot/dts/overlays/imx477_378-overlay.dtsi#L32

The driver ought to be swapped to using `pm_runtime_mark_last_busy` and  `pm_runtime_put_autosuspend` to defer actually powering down, equivalent to https://github.com/torvalds/linux/commit/a8c3e0c1bf1e97b5ee094951ed0f1e57e3b378c7 for imx290. (Please note https://github.com/torvalds/linux/commit/6f6fbd9a0c5a75eee0618c1499cf73cc770b3f52 for later kernels).

Caching of register values has some benefit, but I believe there are better approaches using regmap. It does need some care should a software reset ever be sent because regmap will have no idea about it.
The latest changes to imx477 to use CCI_REG are now using regmap underneath, but configured not to cache anything.

**Comment by thenickdude** [comment]
> It does need some care should a software reset ever be sent because regmap will have no idea about it.

Software reset, if present, is already broken with the original driver, because the *only* thing that can clear the "common_regs_written" flag is imx477_power_off(). So the situation does not get any worse with caching added, so long as the cache is also cleared when common_regs_written is.
