### ISSUE TITLE
RuntimeError: deque mutated during iteration in CircularOutput.py

### ISSUE THREAD

**Issue by sandyol55** [raspberrypi/picamera2#129]
Error raised when called from capture.circular.py example.

Error is inconsistent and usually occurs during a run of multiple motion triggers and captures.

Seems to be related to either size of mainstream video set up in capture.circular.py or to buffersize in circular.output.py .

As outlined in forum report some video size options seem more likely to trigger it than others.

**Comment by davidplowman** [comment]
Fixed by https://github.com/raspberrypi/picamera2/pull/133

Obviously we'll release an updated version soon, in the meantime `pip3 install git+https://github.com/raspberrypi/picamera.git` would probably install the bleeding edge version for you. (Or you git simply clone it for yourself and update your PYTHONPATH to make sure you pick that one up.)

I'll close this one now, but please get back to us if anything else shows up.
