### ISSUE TITLE
[HOW-TO] Check when ExposureTime is set

### ISSUE THREAD

**Issue by mikkelam** [raspberrypi/picamera2#340]
Is there a way to check when the setting of `ExposureTime` has been applied? 

Looking at https://github.com/raspberrypi/picamera2/blob/main/examples/controls_3.py There's just sleeps scattered around, but I'm trying to minimize that, avoid it or even be perfectly sure that it's applied. I guess I can keep taking pictures and comparing the metadata, but is there a better way?

Thanks!

**Comment by davidplowman** [comment]
There is actually work on this very subject underway at the moment and that should improve the situation here, though it's not quite ready yet.

In the meantime, your best bet is probably to call capture_request and look at the metadata for the values you wanted. Alternatively, if you can set the exposure while the camera is stopped then you're guaranteed to have those values as soon as the camera starts, though stopping and starting the camera is relatively slow.

**Comment by davidplowman** [comment]
I'm afraid to say that things haven't progressed. We did do an implementation that lets you know when settings have been applied, but we haven't been able to upstream this. We're going to bring this up again, but as you can tell, it's taking time.

Can you say anything more about your application? There are quite a few folks who have been able to pipeline exposure changes frame by frame so that they can mostly get them to change "back to back". Would that help?

**Comment by davidplowman** [comment]
The idea is that you have a list of exposures/gains that you want.

Every time a frame comes back you check if it's one of the ones you wanted. And you also set the controls to request the next exposure/gain pair from your list that you haven't seen yet. So you're always cycling through that list of exposures/gains that you haven't seen yet. Mostly they come back in the order you want but it's not guaranteed because interrupt timing can occasionally cause you to fail to apply a new exposure.

There's some code here:
https://github.com/raspberrypi/picamera2/issues/399#issuecomment-1311590132

The work that I referred to above gives you a tidier way of doing this.
