### ISSUE TITLE
[HOW-TO] load all parameters of the specific .json file of your camera

### ISSUE THREAD

**Issue by Petros626** [raspberrypi/picamera2#595]
Hello guys,

companies like Waveshare sell different camera models, and `libcamera-apps` provide several configuration files (tuning file) to get the best picture. 

I saw here an example how to load one parameter of a `.json file `:
https://github.com/raspberrypi/picamera2/blob/5858f49b1e6628b236000a0191ecee448fe2c0d9/examples/tuning_file.py

Is there an elegant way to load the complete `.json` file so that all these estimated params can be loaded, before taking pictures?

Thanks in advance

**Comment by davidplowman** [comment]
As things stand you can only choose which tuning file gets loaded when you open Picamera2. This is fairly hard-coded into libcamera as things stand.

The easiest thing to do is simply to create your own tuning file, particularly if you want to fiddle with quite a few parameters. They're straightforward JSON files and you can edit them as you wish, and indeed a number of folks have done so. There is quite a lot of information [here](https://datasheets.raspberrypi.com/camera/raspberry-pi-camera-guide.pdf) (see chapter 5).

Are the edits you need to make specific to your application, or to the module that you are using? In the latter case it would be ideal to make the changes and submit the revised tuning file upstream to libcamera so that others can benefit. In principle you might hope that manufacturers would do this where it might be helpful.

**Comment by davidplowman** [comment]
Yes, everyone gets these files. In an ideal world where folks contribute tuning files for more camera modules to upstream libcamera, then everyone will get those too.

**Comment by Petros626** [comment]
Oh now I understand, unfortunately I don't have a new tuning file to contribute, but if I do then I will request it as pull requests.

**Comment by davidplowman** [comment]
No problem. If you do ever want us to commit a tuning file for a specific module that you think might help others, then do let us know and we can post it to upstream libcamera. Thanks!

**Comment by Petros626** [comment]
@davidplowman quick question about the post, do I need to explicitly call each parameter from the tuning file or is passing it to the Picamera2() constructor enough to load all parameters?

**Comment by davidplowman** [comment]
Loading the tuning file you want and passing it to the constructor is enough.
