### ISSUE TITLE
[BUG] expanding user

### ISSUE THREAD

**Issue by Vincent-Stragier** [raspberrypi/picamera2#733]
Hi,

I think expanding the user this way (line 14) could lead to some bugs:
https://github.com/raspberrypi/picamera2/blob/dd984341d3fda13f1c08c41dc93e25625853bcfe/picamera2/__init__.py#L13-L22

In this [SO answer](https://stackoverflow.com/a/14103180/10949679), the author explains that the user directory is not always `/home/<user>`. Also, `dir` is a built-in function in Python. I would rewrite the code like so:

```python
def _set_configuration_file(filename):
    user_directory = os.path.expanduser("~")
    dirs = [
        os.path.join(
            user_directory,
            "libcamera/src/libcamera/pipeline/rpi/vc4/data"
        ),
        "/usr/local/share/libcamera/pipeline/rpi/vc4",
        "/usr/share/libcamera/pipeline/rpi/vc4"]

    for directory in dirs:
        file = os.path.join(directory, filename)

        if os.path.isfile(file):
            os.environ['LIBCAMERA_RPI_CONFIG_FILE'] = file
            break
```

Regards,
Vincent

**Comment by davidplowman** [comment]
Hi, thanks for the suggestion. That might be a good candidate for a PR, if you'd like to submit one? Please read our [contribution guidelines](https://github.com/raspberrypi/picamera2#contributing) so that we can get through the process easily and quickly. Thanks!

(Just a minor warning that I think this is the new 3.10 release... but which we aren't "officially" distributing without some extra libcamera updates. Hopefully it will only be a few days at most for this, but just to let you know that things are not quite perfect at the minute.)
