### ISSUE TITLE
[HOW-TO] capture an image with no buffered pixels

### ISSUE THREAD

**Issue by mikkelam** [raspberrypi/picamera2#847]
**Describe what it is that you want to accomplish**
I have a scenario where im trying to turn on  some light, capture an image then turn on some other light and capture another image.

Due to this, I have to get my image with no buffered content, that is, i  need the image to only start captuing when i ask for it. I seem to get some leaking from image A into image B currently.

**Describe alternatives you've considered**
In the meantime, im just snapping two image and discarding the first one - that seems to do the trick. Unfortunately i need to run my program fast, as there are many subjects and light combinations i use.

algorithm example:
```python
imgs = []
for led in led_array:
  #turn on the led here

  _ = picamera.capture_array()
  imgs.append(picamera.capture_array()

```

I hopy my question is understandable. Thanks for this amazing project.

**Comment by davidplowman** [comment]
This might be quite tricky, and may depend on the framerates you want, the capture rate that you want, the rate at which the lights get turned on/off and so on. I don't know if you want to change the camera exposure too, which could make it even more challenging.

I think the problems come from the fact that there's an awful lot of pipelining going on:

* There are a number of buffers queued up in libcamera. You need several if you want to get the full camera framerate.
* Most cameras are rolling shutter cameras, so the actually period for which any part of the image is exposed can be difficult to determine. What sensor are you using? Is it a rolling shutter sensor?
* Picamera2 always holds on to the previous frame until it's replaced, though that's easy to disable.
* If you want to change the camera exposure, that takes at least 2 frames as well, and may get backed up behind the libcamera queue.

For the moment, let's assume we're going to leave the camera running (starting and stopping it is very slow, costing 100s of milliseconds). Maybe the first thing to do is understand all the timestamps and what they mean. In theory you can then compare these against the time at which you turned on your LEDs.

Every frame has a 'SensorTimestamp' in its metadata. This is the time the first pixel was read out of the sensor for that frame, and you can compare it against the result of (for example) `time.monotonic()`.

That metadata also has the 'ExposureTime'. You can subtract this (this is in ms, not ns, I think) from the 'SensorTimestamp' to find out when the first pixel started being exposed. If you're sure your LED was on at that moment, then your frame is being exposed with that LED lit up as you expect.

You might also want to know the last moment of exposure of the last pixel of the frame. To find this you should look up the minimum frame time for the camera mode, and add it to the 'SensorTimestamp'. You can find that in `picam2.camera_controls['FrameDurationLimits']`. I think it's the first number (also microseconds, probably).

Maybe try that first and see if it behaves correctly as I've described it. If you want to change the exposure, that's going to be harder because those changes occur at some point "in the future". Though the timestamps and metadata should correctly reflect what's going on. If you are going to change the exposure time, it often works better with a fixed framerate, in fact I think this is required for imx477 (HQ cam), maybe not with the others.

**Comment by davidplowman** [comment]
Hi again, no don't set `buffer_count=1`, that would cause you to drop every other camera frame. Reducing the `buffer_count` can reduce some of the pipelining delays, but you should have a minimum of `buffer_count=3` to maintain the full camera rate. You may need to go higher than that if your system gets sporadically busy.

To disable the frame that Picamera2 holds on to, use `queue=False` in the call that creates the configuration. But you will still have all the other pipelining issues, and complexities in figuring out exactly when the frame was exposed.

**Comment by davidplowman** [comment]
I'm afraid that makes no difference. It's all about the buffers queued up for the camera to fill. The root cause of all this is really that the camera is asynchronous and just dumps pixels to memory whenever it wants, and you have to be sure to have a buffer there waiting for it.

Definitely have a play with the buffer count, but I would recommend checking your SensorTimestamps carefully and comparing against the current time to gain a good feel for what's going on!
